/**
 * loopback-boilerplate
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Branch;
import io.swagger.client.model.DeliveryDetail;
import java.util.*;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Delivery {
  
  @SerializedName("branchFrom")
  private Double branchFrom = null;
  @SerializedName("branchTo")
  private Double branchTo = null;
  @SerializedName("deliveryDate")
  private Date deliveryDate = null;
  @SerializedName("remarks")
  private String remarks = null;
  @SerializedName("id")
  private Double id = null;
  @SerializedName("deliveryDetail")
  private List<DeliveryDetail> deliveryDetail = null;
  @SerializedName("branchFromDetail")
  private Branch branchFromDetail = null;
  @SerializedName("branchToDetail")
  private Branch branchToDetail = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getBranchFrom() {
    return branchFrom;
  }
  public void setBranchFrom(Double branchFrom) {
    this.branchFrom = branchFrom;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getBranchTo() {
    return branchTo;
  }
  public void setBranchTo(Double branchTo) {
    this.branchTo = branchTo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getDeliveryDate() {
    return deliveryDate;
  }
  public void setDeliveryDate(Date deliveryDate) {
    this.deliveryDate = deliveryDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRemarks() {
    return remarks;
  }
  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<DeliveryDetail> getDeliveryDetail() {
    return deliveryDetail;
  }
  public void setDeliveryDetail(List<DeliveryDetail> deliveryDetail) {
    this.deliveryDetail = deliveryDetail;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Branch getBranchFromDetail() {
    return branchFromDetail;
  }
  public void setBranchFromDetail(Branch branchFromDetail) {
    this.branchFromDetail = branchFromDetail;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Branch getBranchToDetail() {
    return branchToDetail;
  }
  public void setBranchToDetail(Branch branchToDetail) {
    this.branchToDetail = branchToDetail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Delivery delivery = (Delivery) o;
    return (this.branchFrom == null ? delivery.branchFrom == null : this.branchFrom.equals(delivery.branchFrom)) &&
        (this.branchTo == null ? delivery.branchTo == null : this.branchTo.equals(delivery.branchTo)) &&
        (this.deliveryDate == null ? delivery.deliveryDate == null : this.deliveryDate.equals(delivery.deliveryDate)) &&
        (this.remarks == null ? delivery.remarks == null : this.remarks.equals(delivery.remarks)) &&
        (this.id == null ? delivery.id == null : this.id.equals(delivery.id)) &&
        (this.deliveryDetail == null ? delivery.deliveryDetail == null : this.deliveryDetail.equals(delivery.deliveryDetail)) &&
        (this.branchFromDetail == null ? delivery.branchFromDetail == null : this.branchFromDetail.equals(delivery.branchFromDetail)) &&
        (this.branchToDetail == null ? delivery.branchToDetail == null : this.branchToDetail.equals(delivery.branchToDetail));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.branchFrom == null ? 0: this.branchFrom.hashCode());
    result = 31 * result + (this.branchTo == null ? 0: this.branchTo.hashCode());
    result = 31 * result + (this.deliveryDate == null ? 0: this.deliveryDate.hashCode());
    result = 31 * result + (this.remarks == null ? 0: this.remarks.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.deliveryDetail == null ? 0: this.deliveryDetail.hashCode());
    result = 31 * result + (this.branchFromDetail == null ? 0: this.branchFromDetail.hashCode());
    result = 31 * result + (this.branchToDetail == null ? 0: this.branchToDetail.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Delivery {\n");
    
    sb.append("  branchFrom: ").append(branchFrom).append("\n");
    sb.append("  branchTo: ").append(branchTo).append("\n");
    sb.append("  deliveryDate: ").append(deliveryDate).append("\n");
    sb.append("  remarks: ").append(remarks).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  deliveryDetail: ").append(deliveryDetail).append("\n");
    sb.append("  branchFromDetail: ").append(branchFromDetail).append("\n");
    sb.append("  branchToDetail: ").append(branchToDetail).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
