/**
 * loopback-boilerplate
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ItemVariantStock {
  
  @SerializedName("itemVariantId")
  private Double itemVariantId = null;
  @SerializedName("quantity")
  private Double quantity = null;
  @SerializedName("id")
  private Double id = null;
  @SerializedName("branchId")
  private Double branchId = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Double getItemVariantId() {
    return itemVariantId;
  }
  public void setItemVariantId(Double itemVariantId) {
    this.itemVariantId = itemVariantId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Double getQuantity() {
    return quantity;
  }
  public void setQuantity(Double quantity) {
    this.quantity = quantity;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getBranchId() {
    return branchId;
  }
  public void setBranchId(Double branchId) {
    this.branchId = branchId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemVariantStock itemVariantStock = (ItemVariantStock) o;
    return (this.itemVariantId == null ? itemVariantStock.itemVariantId == null : this.itemVariantId.equals(itemVariantStock.itemVariantId)) &&
        (this.quantity == null ? itemVariantStock.quantity == null : this.quantity.equals(itemVariantStock.quantity)) &&
        (this.id == null ? itemVariantStock.id == null : this.id.equals(itemVariantStock.id)) &&
        (this.branchId == null ? itemVariantStock.branchId == null : this.branchId.equals(itemVariantStock.branchId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.itemVariantId == null ? 0: this.itemVariantId.hashCode());
    result = 31 * result + (this.quantity == null ? 0: this.quantity.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.branchId == null ? 0: this.branchId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemVariantStock {\n");
    
    sb.append("  itemVariantId: ").append(itemVariantId).append("\n");
    sb.append("  quantity: ").append(quantity).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  branchId: ").append(branchId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
