/**
 * loopback-boilerplate
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LogTransactionPaymentDetail {
  
  @SerializedName("paymentDetailId")
  private Double paymentDetailId = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("remarks")
  private String remarks = null;
  @SerializedName("createdBy")
  private Double createdBy = null;
  @SerializedName("lastUpdatedBy")
  private Double lastUpdatedBy = null;
  @SerializedName("branchId")
  private Double branchId = null;
  @SerializedName("companyId")
  private Double companyId = null;
  @SerializedName("id")
  private Double id = null;
  @SerializedName("createdAt")
  private Date createdAt = null;
  @SerializedName("updatedAt")
  private Date updatedAt = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Double getPaymentDetailId() {
    return paymentDetailId;
  }
  public void setPaymentDetailId(Double paymentDetailId) {
    this.paymentDetailId = paymentDetailId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRemarks() {
    return remarks;
  }
  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getCreatedBy() {
    return createdBy;
  }
  public void setCreatedBy(Double createdBy) {
    this.createdBy = createdBy;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getLastUpdatedBy() {
    return lastUpdatedBy;
  }
  public void setLastUpdatedBy(Double lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getBranchId() {
    return branchId;
  }
  public void setBranchId(Double branchId) {
    this.branchId = branchId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getCompanyId() {
    return companyId;
  }
  public void setCompanyId(Double companyId) {
    this.companyId = companyId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getUpdatedAt() {
    return updatedAt;
  }
  public void setUpdatedAt(Date updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogTransactionPaymentDetail logTransactionPaymentDetail = (LogTransactionPaymentDetail) o;
    return (this.paymentDetailId == null ? logTransactionPaymentDetail.paymentDetailId == null : this.paymentDetailId.equals(logTransactionPaymentDetail.paymentDetailId)) &&
        (this.status == null ? logTransactionPaymentDetail.status == null : this.status.equals(logTransactionPaymentDetail.status)) &&
        (this.remarks == null ? logTransactionPaymentDetail.remarks == null : this.remarks.equals(logTransactionPaymentDetail.remarks)) &&
        (this.createdBy == null ? logTransactionPaymentDetail.createdBy == null : this.createdBy.equals(logTransactionPaymentDetail.createdBy)) &&
        (this.lastUpdatedBy == null ? logTransactionPaymentDetail.lastUpdatedBy == null : this.lastUpdatedBy.equals(logTransactionPaymentDetail.lastUpdatedBy)) &&
        (this.branchId == null ? logTransactionPaymentDetail.branchId == null : this.branchId.equals(logTransactionPaymentDetail.branchId)) &&
        (this.companyId == null ? logTransactionPaymentDetail.companyId == null : this.companyId.equals(logTransactionPaymentDetail.companyId)) &&
        (this.id == null ? logTransactionPaymentDetail.id == null : this.id.equals(logTransactionPaymentDetail.id)) &&
        (this.createdAt == null ? logTransactionPaymentDetail.createdAt == null : this.createdAt.equals(logTransactionPaymentDetail.createdAt)) &&
        (this.updatedAt == null ? logTransactionPaymentDetail.updatedAt == null : this.updatedAt.equals(logTransactionPaymentDetail.updatedAt));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.paymentDetailId == null ? 0: this.paymentDetailId.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.remarks == null ? 0: this.remarks.hashCode());
    result = 31 * result + (this.createdBy == null ? 0: this.createdBy.hashCode());
    result = 31 * result + (this.lastUpdatedBy == null ? 0: this.lastUpdatedBy.hashCode());
    result = 31 * result + (this.branchId == null ? 0: this.branchId.hashCode());
    result = 31 * result + (this.companyId == null ? 0: this.companyId.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.updatedAt == null ? 0: this.updatedAt.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogTransactionPaymentDetail {\n");
    
    sb.append("  paymentDetailId: ").append(paymentDetailId).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  remarks: ").append(remarks).append("\n");
    sb.append("  createdBy: ").append(createdBy).append("\n");
    sb.append("  lastUpdatedBy: ").append(lastUpdatedBy).append("\n");
    sb.append("  branchId: ").append(branchId).append("\n");
    sb.append("  companyId: ").append(companyId).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  updatedAt: ").append(updatedAt).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
