/**
 * loopback-boilerplate
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.PurchaseDetail;
import java.util.*;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Purchase {
  
  @SerializedName("invoiceNo")
  private String invoiceNo = null;
  @SerializedName("supplierName")
  private String supplierName = null;
  @SerializedName("totalAmount")
  private Double totalAmount = null;
  @SerializedName("remarks")
  private String remarks = null;
  @SerializedName("purchaseDate")
  private Date purchaseDate = null;
  @SerializedName("id")
  private Double id = null;
  @SerializedName("purchaseDetail")
  private List<PurchaseDetail> purchaseDetail = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getInvoiceNo() {
    return invoiceNo;
  }
  public void setInvoiceNo(String invoiceNo) {
    this.invoiceNo = invoiceNo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSupplierName() {
    return supplierName;
  }
  public void setSupplierName(String supplierName) {
    this.supplierName = supplierName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getTotalAmount() {
    return totalAmount;
  }
  public void setTotalAmount(Double totalAmount) {
    this.totalAmount = totalAmount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRemarks() {
    return remarks;
  }
  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getPurchaseDate() {
    return purchaseDate;
  }
  public void setPurchaseDate(Date purchaseDate) {
    this.purchaseDate = purchaseDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<PurchaseDetail> getPurchaseDetail() {
    return purchaseDetail;
  }
  public void setPurchaseDetail(List<PurchaseDetail> purchaseDetail) {
    this.purchaseDetail = purchaseDetail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Purchase purchase = (Purchase) o;
    return (this.invoiceNo == null ? purchase.invoiceNo == null : this.invoiceNo.equals(purchase.invoiceNo)) &&
        (this.supplierName == null ? purchase.supplierName == null : this.supplierName.equals(purchase.supplierName)) &&
        (this.totalAmount == null ? purchase.totalAmount == null : this.totalAmount.equals(purchase.totalAmount)) &&
        (this.remarks == null ? purchase.remarks == null : this.remarks.equals(purchase.remarks)) &&
        (this.purchaseDate == null ? purchase.purchaseDate == null : this.purchaseDate.equals(purchase.purchaseDate)) &&
        (this.id == null ? purchase.id == null : this.id.equals(purchase.id)) &&
        (this.purchaseDetail == null ? purchase.purchaseDetail == null : this.purchaseDetail.equals(purchase.purchaseDetail));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.invoiceNo == null ? 0: this.invoiceNo.hashCode());
    result = 31 * result + (this.supplierName == null ? 0: this.supplierName.hashCode());
    result = 31 * result + (this.totalAmount == null ? 0: this.totalAmount.hashCode());
    result = 31 * result + (this.remarks == null ? 0: this.remarks.hashCode());
    result = 31 * result + (this.purchaseDate == null ? 0: this.purchaseDate.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.purchaseDetail == null ? 0: this.purchaseDetail.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Purchase {\n");
    
    sb.append("  invoiceNo: ").append(invoiceNo).append("\n");
    sb.append("  supplierName: ").append(supplierName).append("\n");
    sb.append("  totalAmount: ").append(totalAmount).append("\n");
    sb.append("  remarks: ").append(remarks).append("\n");
    sb.append("  purchaseDate: ").append(purchaseDate).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  purchaseDetail: ").append(purchaseDetail).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
