/**
 * loopback-boilerplate
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.ItemVariant;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PurchaseDetail {
  
  @SerializedName("purchaseId")
  private Double purchaseId = null;
  @SerializedName("itemVariantId")
  private Double itemVariantId = null;
  @SerializedName("quantity")
  private Double quantity = null;
  @SerializedName("id")
  private Double id = null;
  @SerializedName("itemVariant")
  private ItemVariant itemVariant = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Double getPurchaseId() {
    return purchaseId;
  }
  public void setPurchaseId(Double purchaseId) {
    this.purchaseId = purchaseId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getItemVariantId() {
    return itemVariantId;
  }
  public void setItemVariantId(Double itemVariantId) {
    this.itemVariantId = itemVariantId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getQuantity() {
    return quantity;
  }
  public void setQuantity(Double quantity) {
    this.quantity = quantity;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ItemVariant getItemVariant() {
    return itemVariant;
  }
  public void setItemVariant(ItemVariant itemVariant) {
    this.itemVariant = itemVariant;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseDetail purchaseDetail = (PurchaseDetail) o;
    return (this.purchaseId == null ? purchaseDetail.purchaseId == null : this.purchaseId.equals(purchaseDetail.purchaseId)) &&
        (this.itemVariantId == null ? purchaseDetail.itemVariantId == null : this.itemVariantId.equals(purchaseDetail.itemVariantId)) &&
        (this.quantity == null ? purchaseDetail.quantity == null : this.quantity.equals(purchaseDetail.quantity)) &&
        (this.id == null ? purchaseDetail.id == null : this.id.equals(purchaseDetail.id)) &&
        (this.itemVariant == null ? purchaseDetail.itemVariant == null : this.itemVariant.equals(purchaseDetail.itemVariant));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.purchaseId == null ? 0: this.purchaseId.hashCode());
    result = 31 * result + (this.itemVariantId == null ? 0: this.itemVariantId.hashCode());
    result = 31 * result + (this.quantity == null ? 0: this.quantity.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.itemVariant == null ? 0: this.itemVariant.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseDetail {\n");
    
    sb.append("  purchaseId: ").append(purchaseId).append("\n");
    sb.append("  itemVariantId: ").append(itemVariantId).append("\n");
    sb.append("  quantity: ").append(quantity).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  itemVariant: ").append(itemVariant).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
