/**
 * loopback-boilerplate
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.ItemVariant;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SaleDetail {
  
  @SerializedName("saleId")
  private Double saleId = null;
  @SerializedName("unitPrice")
  private Double unitPrice = null;
  @SerializedName("basePrice")
  private Double basePrice = null;
  @SerializedName("itemVariantId")
  private Double itemVariantId = null;
  @SerializedName("quantity")
  private Double quantity = null;
  @SerializedName("amount")
  private Double amount = null;
  @SerializedName("id")
  private Double id = null;
  @SerializedName("itemVariant")
  private ItemVariant itemVariant = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Double getSaleId() {
    return saleId;
  }
  public void setSaleId(Double saleId) {
    this.saleId = saleId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getUnitPrice() {
    return unitPrice;
  }
  public void setUnitPrice(Double unitPrice) {
    this.unitPrice = unitPrice;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getBasePrice() {
    return basePrice;
  }
  public void setBasePrice(Double basePrice) {
    this.basePrice = basePrice;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getItemVariantId() {
    return itemVariantId;
  }
  public void setItemVariantId(Double itemVariantId) {
    this.itemVariantId = itemVariantId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getQuantity() {
    return quantity;
  }
  public void setQuantity(Double quantity) {
    this.quantity = quantity;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getAmount() {
    return amount;
  }
  public void setAmount(Double amount) {
    this.amount = amount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ItemVariant getItemVariant() {
    return itemVariant;
  }
  public void setItemVariant(ItemVariant itemVariant) {
    this.itemVariant = itemVariant;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaleDetail saleDetail = (SaleDetail) o;
    return (this.saleId == null ? saleDetail.saleId == null : this.saleId.equals(saleDetail.saleId)) &&
        (this.unitPrice == null ? saleDetail.unitPrice == null : this.unitPrice.equals(saleDetail.unitPrice)) &&
        (this.basePrice == null ? saleDetail.basePrice == null : this.basePrice.equals(saleDetail.basePrice)) &&
        (this.itemVariantId == null ? saleDetail.itemVariantId == null : this.itemVariantId.equals(saleDetail.itemVariantId)) &&
        (this.quantity == null ? saleDetail.quantity == null : this.quantity.equals(saleDetail.quantity)) &&
        (this.amount == null ? saleDetail.amount == null : this.amount.equals(saleDetail.amount)) &&
        (this.id == null ? saleDetail.id == null : this.id.equals(saleDetail.id)) &&
        (this.itemVariant == null ? saleDetail.itemVariant == null : this.itemVariant.equals(saleDetail.itemVariant));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.saleId == null ? 0: this.saleId.hashCode());
    result = 31 * result + (this.unitPrice == null ? 0: this.unitPrice.hashCode());
    result = 31 * result + (this.basePrice == null ? 0: this.basePrice.hashCode());
    result = 31 * result + (this.itemVariantId == null ? 0: this.itemVariantId.hashCode());
    result = 31 * result + (this.quantity == null ? 0: this.quantity.hashCode());
    result = 31 * result + (this.amount == null ? 0: this.amount.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.itemVariant == null ? 0: this.itemVariant.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaleDetail {\n");
    
    sb.append("  saleId: ").append(saleId).append("\n");
    sb.append("  unitPrice: ").append(unitPrice).append("\n");
    sb.append("  basePrice: ").append(basePrice).append("\n");
    sb.append("  itemVariantId: ").append(itemVariantId).append("\n");
    sb.append("  quantity: ").append(quantity).append("\n");
    sb.append("  amount: ").append(amount).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  itemVariant: ").append(itemVariant).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
