/**
 * loopback-boilerplate
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UserInfo {
  
  @SerializedName("userId")
  private Double userId = null;
  @SerializedName("companyId")
  private Double companyId = null;
  @SerializedName("branchId")
  private Double branchId = null;
  @SerializedName("userRole")
  private String userRole = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("id")
  private Double id = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getUserId() {
    return userId;
  }
  public void setUserId(Double userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getCompanyId() {
    return companyId;
  }
  public void setCompanyId(Double companyId) {
    this.companyId = companyId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getBranchId() {
    return branchId;
  }
  public void setBranchId(Double branchId) {
    this.branchId = branchId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserRole() {
    return userRole;
  }
  public void setUserRole(String userRole) {
    this.userRole = userRole;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserInfo userInfo = (UserInfo) o;
    return (this.userId == null ? userInfo.userId == null : this.userId.equals(userInfo.userId)) &&
        (this.companyId == null ? userInfo.companyId == null : this.companyId.equals(userInfo.companyId)) &&
        (this.branchId == null ? userInfo.branchId == null : this.branchId.equals(userInfo.branchId)) &&
        (this.userRole == null ? userInfo.userRole == null : this.userRole.equals(userInfo.userRole)) &&
        (this.status == null ? userInfo.status == null : this.status.equals(userInfo.status)) &&
        (this.id == null ? userInfo.id == null : this.id.equals(userInfo.id));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.companyId == null ? 0: this.companyId.hashCode());
    result = 31 * result + (this.branchId == null ? 0: this.branchId.hashCode());
    result = 31 * result + (this.userRole == null ? 0: this.userRole.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserInfo {\n");
    
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  companyId: ").append(companyId).append("\n");
    sb.append("  branchId: ").append(branchId).append("\n");
    sb.append("  userRole: ").append(userRole).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
